FROM node:20-alpine AS builder

WORKDIR /app
ARG VITE_BASE_URL
ENV VITE_BASE_URL=${VITE_BASE_URL}

COPY frontend/package.json frontend/package-lock.json ./
COPY config /config
COPY libs /libs
RUN npm ci

COPY frontend ./

RUN npm run build

FROM nginx:1.25-alpine

COPY frontend/nginx.prod.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]