version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-service
    ports:
      - "5444:3000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/docs:/app/docs
      - ./libs:/libs
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-service
    ports:
      - "5445:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend