version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: f1_champions
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-service
    ports:
      - "5444:3000"
      - "5555:5555"
    volumes:
      - ./backend/src:/app/src
      - ./backend/docs:/app/docs
      - ./libs:/libs
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-service
    ports:
      - "5445:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

volumes:
  postgres-data: