version: '3.8'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: f1_champions
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb:0.14.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/f1_champions?sslmode=disable
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend-service
    ports:
      - "5444:3000"
      - "5555:5555"
    volumes:
      - ./backend/src:/app/src
      - ./backend/docs:/app/docs
      - ./libs:/libs
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/f1_champions
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-service
    ports:
      - "5445:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

volumes:
  postgres-data:
  redis-data: