openapi: 3.1.0
info:
  title: F1 Champions API
  description: API for accessing F1 Champions data
  version: 1.0.0

  servers:
  - url: /api
    description: Local development server
  
paths:
  /health:
    get:
      summary: API health check
      description: Returns the API status and uptime
      tags:
        - Health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /seasons:
    get:
      summary: List all available F1 seasons from 2005 onwards
      description: Returns a list of F1 seasons with their IDs and wiki URLs
      tags:
        - Seasons
      responses:
        '200':
          description: A list of F1 seasons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SeasonsResponse'


  /seasons/{seasonId}/races:
    get:
      summary: Get details of a specific F1 season
      description: Returns all the races in a specific F1 season
      tags:
        - Seasons
      parameters:
        - name: seasonId
          in: path
          required: true
          description: The ID of the F1 season (e.g., 2020)
          schema:
            type: integer
            example: 2020
      responses:
        '200':
          description: Details of the specified F1 season
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RacesResponse'
        '404':
          description: Season not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - uptime
      properties:
        status:
          type: string
          example: ok
        uptime:
          type: number
          description: Time in seconds since the API started
          example: 123.456
    
    Season:
      type: object
      required:
        - id
        - year
        - url
      properties:
        id:
          type: integer
          example: 12
        year:
          type: integer
          example: 2020
        url:
          type: string
          format: uri
          example: https://en.wikipedia.org/wiki/2020_Formula_One_World_Championship

    SeasonsResponse:
      type: array
      items:
        $ref: '#/components/schemas/Season'

    Driver:
      type: object
      required:
        - id
        - givenName
        - familyName
        - isSeasonChampion
      properties:
        id:
          type: string
          example: "hamilton"
        givenName:
          type: string
          example: "Lewis"
        familyName:
          type: string
          example: "Hamilton"
        isSeasonChampion:
          type: boolean
          example: true

    Race:
      type: object
      required:
        - driver
        - season
        - date
        - id
        - name
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "Bahrain Grand Prix"
        date:
          type: string
          format: date
          example: "2020-12-13T00:00:00Z"
        season:
          type: integer
          example: 2020
        driver:
          type: object
          $ref: '#/components/schemas/Driver'
          example:
            id: "hamilton"
            givenName: "Lewis"
            familyName: "Hamilton"
            isSeasonChampion: true

    RacesResponse:
      type: array
      items:
        $ref: '#/components/schemas/Race'

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "An error occurred"
        message:
          type: string
          example: "Detailed error message"
        code:
          type: integer
          example: 500