openapi: 3.1.0
info:
  title: F1 Champions API
  description: API for accessing F1 Champions data
  version: 1.0.0

  servers:
  - url: /api
    description: Local development server
  
paths:
  /health:
    get:
      summary: API health check
      description: Returns the API status and uptime
      tags:
        - Health
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    HealthResponse:
      type: object
      required:
        - status
        - uptime
      properties:
        status:
          type: string
          example: ok
        uptime:
          type: number
          description: Time in seconds since the API started
          example: 123.456