name: Backend CI/CD
on:
  push:
    branches: [ci]
    paths:
      - 'backend/**'
      - 'libs/**'
      - 'config/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'libs/**'
      - 'config/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
      - name: Install & Lint
        run: npm ci && npm run lint
        working-directory: backend
      - name: Test
        run: npm test
        working-directory: backend

  build-push:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push BE Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            REDIS_URL=${{ secrets.REDIS_URL }}
  
  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: backend
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }} --detach